
import { StyleDefinition } from './types';

export const UI_STYLES: StyleDefinition[] = [
  {
    id: 'minimalism',
    name: 'Minimalism & Swiss Style',
    keywords: 'Clean, simple, spacious, functional, white space, high contrast, geometric, sans-serif, grid-based, essential.',
    colorSchemes: 'Monochromatic, Black & White, Neutral Palette (Beige, Grey), Primary colors as accents.',
    effects: 'Subtle hover effects, smooth transitions, sharp shadows (if any), clear typography hierarchy, fast loading.',
    description: 'Focuses on the essential content with ample whitespace and strict typography.',
  },
  {
    id: 'neumorphism',
    name: 'Neumorphism',
    keywords: 'Soft UI, embossed, debossed, convex, concave, light source, subtle depth, rounded corners, monochromatic.',
    colorSchemes: 'Light pastel colors, soft gradients, low-contrast colors, dominant single color with light/dark variations.',
    effects: 'Soft box-shadows (multiple layers), smooth press/release animation, subtle inner shadow, no hard lines.',
    description: 'A "Soft UI" that mimics physical extrusions using light and shadow.',
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    keywords: 'Frosted glass, transparent, blurred background, layered, vibrant background, light source, depth.',
    colorSchemes: 'Translucent colors, vibrant background colors (blue, purple, pink), white/light text.',
    effects: 'Background blur (backdrop-filter), subtle border, light source reflection, layered Z-index structure.',
    description: 'Simulates frosted glass floating over a vibrant background.',
  },
  {
    id: 'brutalism',
    name: 'Brutalism',
    keywords: 'Raw, unpolished, stark, high contrast, plain text, default fonts, visible borders, unstyled links, asymmetric.',
    colorSchemes: 'Primary colors (Red, Blue, Yellow), Black & White, Neon accents, limited palette.',
    effects: 'No smooth transitions, sharp corners, bold typography, visible grid lines, large block elements, intentional "broken" look.',
    description: 'Raw, unpolished aesthetic that disregards conventional beauty for impact.',
  },
  {
    id: '3d-hyperrealism',
    name: '3D & Hyperrealism',
    keywords: 'Depth, realistic textures, 3D models, spatial navigation, tactile, skeuomorphic elements, rich detail.',
    colorSchemes: 'Rich, deep colors, metallic, glossy, matte textures, complex gradients.',
    effects: 'Interactive 3D elements, complex shadows, realistic lighting, physics-based motion, parallax scrolling.',
    description: 'Immersive interfaces that mimic real-world textures and depth.',
  },
  {
    id: 'vibrant-block',
    name: 'Vibrant & Block-based',
    keywords: 'Bold, energetic, playful, block layout, geometric shapes, high color contrast, duotone, modern.',
    colorSchemes: 'Complementary colors, triadic schemes, vibrant contrasts (e.g., Neon Green on Dark Blue), bright pastels.',
    effects: 'Large, distinct sections, animated background patterns, bold hover states, smooth scroll-snap, large typography.',
    description: 'High-energy layouts using bold color blocks and distinct geometry.',
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode (OLED Optimized)',
    keywords: 'Dark theme, low light, high contrast, deep black, midnight blue, eye-friendly, OLED.',
    colorSchemes: 'Deep black (#000000), dark grey (#121212), vibrant accent colors (Neon Green, Electric Blue, Gold) for highlights.',
    effects: 'Minimal glow effects, smooth dark-to-light transitions, reduced white light emission, focus on readability.',
    description: 'Eye-friendly low-light interfaces optimized for contrast and battery.',
  },
  {
    id: 'accessible',
    name: 'Accessible & Ethical',
    keywords: 'High contrast, large text, keyboard navigation, screen reader friendly, WCAG compliant, focus state, clear feedback.',
    colorSchemes: 'WCAG AA/AAA compliant color combinations, high luminosity contrast ratio, simple palette.',
    effects: 'Clear focus rings, ARIA attributes, skip links, responsive design, reduced motion option.',
    description: 'Designed for inclusivity with high legibility and clear navigation.',
  },
  {
    id: 'claymorphism',
    name: 'Claymorphism',
    keywords: 'Soft 3D, chunky, playful, toy-like, bubbly, thick borders, double shadows, rounded edges.',
    colorSchemes: 'Pastel colors, soft gradients, light background, dominant color with light/dark variations.',
    effects: 'Inner and outer shadows (subtle), soft press/release animation, large, fluffy elements, no hard lines.',
    description: 'Friendly, inflated 3D shapes resembling clay or marshmallow.',
  },
  {
    id: 'aurora',
    name: 'Aurora UI',
    keywords: 'Vibrant gradients, smooth blend, Northern Lights effect, mesh gradient, luminous, atmospheric, abstract background.',
    colorSchemes: 'Complementary colors, vibrant colors (Blue, Purple, Pink, Teal), smooth color transitions.',
    effects: 'Large, flowing background gradients, subtle animation of the gradient, depth effect via color layering.',
    description: 'Ethereal backgrounds with moving, blurred mesh gradients.',
  },
  {
    id: 'retro-futurism',
    name: 'Retro-Futurism',
    keywords: 'Vintage sci-fi, 80s aesthetic, neon glow, geometric patterns, CRT scanlines, pixel art, cyberpunk, vaporwave.',
    colorSchemes: 'Neon colors (Electric Blue, Hot Pink, Cyan), deep black background, metallic silver/gold accents, duotone.',
    effects: 'CRT screen effect, neon glow text/borders, glitch effects, animated geometric patterns, monospace fonts.',
    description: 'Nostalgic vision of the future with neon and glitch aesthetics.',
  },
  {
    id: 'bento-grid',
    name: 'Bento Grid',
    keywords: 'Organized, modular, dashboard, card-based, content-first, hierarchical, rounded, structural.',
    colorSchemes: 'Neutral backgrounds (Off-white, faint grey), soft distinct borders, brand colors used only in icons/graphs.',
    effects: 'Strict grid layouts, unified corner radius, "squircle" shapes, very polished spacing.',
    description: 'Modular, compartmentalized design inspired by Japanese Bento boxes.',
  },
  {
    id: 'y2k-acid',
    name: 'Y2K / Acid Graphics',
    keywords: 'Nostalgic, chaotic, chrome, liquid, tribal, playful, experimental.',
    colorSchemes: 'Metallic chrome, hot pink, lime green, electric purple, high saturation, gradients that clash intentionally.',
    effects: 'Chrome typography, liquid/melting shapes, starburst icons, jagged edges, Marquee scrolling text.',
    description: 'Chaotic, futuristic nostalgia from the late 90s and early 2000s.',
  },
  {
    id: 'paper-collage',
    name: 'Paper / Collage',
    keywords: 'Hand-drawn, tactile, human, organic, rough edges, textured, artistic, DIY.',
    colorSchemes: 'Earth tones, paper white, ink black, desaturated vintage colors (sepia, olive).',
    effects: 'Paper textures, ragged edges, tape overlays, handwriting fonts, doodles, overlapping elements.',
    description: 'Organic, tactile feel mimicking physical scrapbooks and paper cutouts.',
  },
  {
    id: 'holographic',
    name: 'Holographic / Iridescent',
    keywords: 'Ethereal, shiny, spectrum, futuristic, clean, mesmerizing, fluid.',
    colorSchemes: 'Silver base with rainbow gradients (pearl, oil slick), pastel neon overlay on white.',
    effects: 'Shimmer effects, moving gradients, metallic sheen, often combined with subtle noise or glass effects.',
    description: 'Shiny, spectrum-filled surfaces that shift colors like a CD or bubble.',
  },
  {
    id: 'terminal-cli',
    name: 'Terminal / CLI',
    keywords: 'Developer-focused, raw, command line, ASCII, technical, keyboard-centric, monochrome.',
    colorSchemes: 'Pure Black (#000000) background, Bright Green (#00FF00) or Amber text.',
    effects: 'Monospace fonts, blinking cursor block, typed-text animations, ASCII art borders, no shadows.',
    description: 'Raw, text-only interfaces celebrating the command line aesthetic.',
  },
  {
    id: 'material-you',
    name: 'Material You',
    keywords: 'Adaptive, dynamic, fluid, personalized, nature-inspired, touch-friendly, Google-standard.',
    colorSchemes: 'Dynamic extraction, pastel tones derived from a seed color.',
    effects: 'Pill shapes, large floating action buttons (FAB), ripple effects, adaptive coloring, elevation via tint.',
    description: 'Adaptive, personalized design language emphasizing fluid shapes and dynamic color.',
  }
];
